import type { Role } from '../types/auth';

export const PERMISSIONS = {
  CAN_VOID_ORDER: 'CAN_VOID_ORDER',
  CAN_VOID_ITEM: 'CAN_VOID_ITEM',
  CAN_APPLY_DISCOUNT: 'CAN_APPLY_DISCOUNT',
  CAN_ACCESS_REPORTS: 'CAN_ACCESS_REPORTS',
  CAN_MANAGE_STAFF: 'CAN_MANAGE_STAFF',
  CAN_ACCESS_POS: 'CAN_ACCESS_POS',
  CAN_ACCESS_KDS: 'CAN_ACCESS_KDS',
} as const;

export type Permission = keyof typeof PERMISSIONS;

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SERVER: [
    PERMISSIONS.CAN_ACCESS_POS,
  ],
  KITCHEN: [
    PERMISSIONS.CAN_ACCESS_KDS,
  ],
  MANAGER: [
    PERMISSIONS.CAN_ACCESS_POS,
    PERMISSIONS.CAN_ACCESS_KDS,
    PERMISSIONS.CAN_VOID_ORDER,
    PERMISSIONS.CAN_VOID_ITEM,
    PERMISSIONS.CAN_APPLY_DISCOUNT,
    PERMISSIONS.CAN_ACCESS_REPORTS,
  ],
  ADMIN: [
    PERMISSIONS.CAN_ACCESS_POS,
    PERMISSIONS.CAN_ACCESS_KDS,
    PERMISSIONS.CAN_VOID_ORDER,
    PERMISSIONS.CAN_VOID_ITEM,
    PERMISSIONS.CAN_APPLY_DISCOUNT,
    PERMISSIONS.CAN_ACCESS_REPORTS,
    PERMISSIONS.CAN_MANAGE_STAFF,
  ],
};

export const hasPermission = (role: Role | undefined, permission: Permission): boolean => {
  if (!role) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
};
